<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAP000317" failures="6" tests="9" name="Test" time="10.155" errors="0" timestamp="2025-07-22T21:26:24 IST">
  <testcase classname="api.testcases.UserTestDD" name="testcreateuser" time="0.007">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.info(String)&amp;quot; because &amp;quot;api.testcases.UserTestDD.Logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.info(String)" because "api.testcases.UserTestDD.Logger" is null
at api.testcases.UserTestDD.testcreateuser(UserTestDD.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testcreateuser -->
  <testcase classname="api.testcases.UserTestDD" name="testcreateuser" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.info(String)&amp;quot; because &amp;quot;api.testcases.UserTestDD.Logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.info(String)" because "api.testcases.UserTestDD.Logger" is null
at api.testcases.UserTestDD.testcreateuser(UserTestDD.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testcreateuser -->
  <testcase classname="api.testcases.UserTestDD" name="testcreateuser" time="0.001">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.logging.log4j.Logger.info(String)&amp;quot; because &amp;quot;api.testcases.UserTestDD.Logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.info(String)" because "api.testcases.UserTestDD.Logger" is null
at api.testcases.UserTestDD.testcreateuser(UserTestDD.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testcreateuser -->
  <testcase classname="api.testcases.UserTestDD" name="testgetUserData" time="2.156">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;404&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at api.testcases.UserTestDD.testgetUserData(UserTestDD.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testgetUserData -->
  <testcase classname="api.testcases.UserTestDD" name="testgetUserData" time="1.245"/>
  <testcase classname="api.testcases.UserTestDD" name="testgetUserData" time="1.224">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;404&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at api.testcases.UserTestDD.testgetUserData(UserTestDD.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testgetUserData -->
  <testcase classname="api.testcases.UserTestDD" name="testdeleteUserData" time="1.356">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;404&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at api.testcases.UserTestDD.testdeleteUserData(UserTestDD.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteUserData -->
  <testcase classname="api.testcases.UserTestDD" name="testdeleteUserData" time="1.524"/>
  <testcase classname="api.testcases.UserTestDD" name="testdeleteUserData" time="1.265"/>
</testsuite> <!-- Test -->
